[tool.poetry]
name = "todopane"
version = "0.1.0"
description = ""
authors = ["Almad <bugs@almad.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tomli = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
